"""Introspect the live Postgres consent-path tables and emit SQLite-compatible DDL.

Run while the Cloud SQL proxy is up on 127.0.0.1:6543. Produces SQLite CREATE TABLE
statements that mirror the real column names/nullability so the offline db_client
(SQLAlchemy + SQLite) serves the consent connector + PKM flows with real parity.
"""

import os

import psycopg2

TABLES = [
    "consent_audit",
    "consent_exports",
    "consent_export_refresh_jobs",
    "internal_access_events",
    "pkm_blobs",
    "pkm_data",
    "pkm_index",
    "pkm_manifests",
    "pkm_manifest_paths",
    "pkm_events",
    "pkm_scope_registry",
    "pkm_default_available_projections",
    "pkm_migration_state",
    # vault + runtime tables required at startup / used by review flow
    "vault_keys",
    "vault_key_wrappers",
    "user_push_tokens",
    "runtime_persona_state",
    "developer_applications",
    "developer_apps",
    "developer_tokens",
    "users",
]


# Postgres type -> SQLite affinity
def sqlite_type(pg_type: str) -> str:
    t = pg_type.lower()
    if any(k in t for k in ("int", "serial", "bigint", "smallint")):
        return "INTEGER"
    if any(k in t for k in ("bool",)):
        return "INTEGER"
    if any(k in t for k in ("json", "jsonb")):
        return "TEXT"  # store JSON as text; db_client json.dumps for non-postgres
    if any(k in t for k in ("timestamp", "date", "time")):
        return "TEXT"
    if any(k in t for k in ("numeric", "decimal", "real", "double", "float")):
        return "REAL"
    if any(k in t for k in ("bytea",)):
        return "BLOB"
    return "TEXT"


def main():
    dsn = dict(
        host="127.0.0.1",
        port=int(os.getenv("DB_PORT", "6543")),
        dbname=os.getenv("DB_NAME", "postgres"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
    )
    conn = psycopg2.connect(**dsn)
    cur = conn.cursor()
    out = []
    out.append("-- Auto-generated SQLite schema mirroring live Postgres consent-path tables.")
    out.append("-- Generated by db/_gen_offline_schema.py against UAT Postgres. Do not hand-edit;")
    out.append("-- regenerate when migrations change consent/PKM/vault columns.\n")
    for table in TABLES:
        cur.execute(
            """
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns
            WHERE table_schema='public' AND table_name=%s
            ORDER BY ordinal_position
            """,
            (table,),
        )
        cols = cur.fetchall()
        if not cols:
            out.append(f"-- WARNING: table {table} not found in live schema, skipped\n")
            continue
        # primary key columns
        cur.execute(
            """
            SELECT a.attname
            FROM pg_index i
            JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
            WHERE i.indrelid = %s::regclass AND i.indisprimary
            """,
            (table,),
        )
        pk = [r[0] for r in cur.fetchall()]
        lines = [f'CREATE TABLE IF NOT EXISTS "{table}" (']
        col_defs = []
        for name, dtype, nullable, _default in cols:
            st = sqlite_type(dtype)
            d = f'  "{name}" {st}'
            # single-col PK inline
            if pk == [name]:
                d += " PRIMARY KEY"
            if nullable == "NO" and pk != [name]:
                d += " NOT NULL"
            col_defs.append(d)
        if len(pk) > 1:
            col_defs.append(f"  PRIMARY KEY ({', '.join(chr(34) + c + chr(34) for c in pk)})")
        lines.append(",\n".join(col_defs))
        lines.append(");")
        out.append("\n".join(lines) + "\n")
    print("\n".join(out))
    conn.close()


if __name__ == "__main__":
    main()
