-- Auto-generated SQLite schema mirroring live Postgres consent-path tables.
-- Generated by db/_gen_offline_schema.py against UAT Postgres. Do not hand-edit;
-- regenerate when migrations change consent/PKM/vault columns.

CREATE TABLE IF NOT EXISTS "consent_audit" (
  "id" INTEGER PRIMARY KEY,
  "token_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "agent_id" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "issued_at" INTEGER NOT NULL,
  "expires_at" INTEGER,
  "revoked_at" INTEGER,
  "metadata" TEXT,
  "token_type" TEXT,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "request_id" TEXT,
  "scope_description" TEXT,
  "poll_timeout_at" INTEGER
);

CREATE TABLE IF NOT EXISTS "consent_exports" (
  "consent_token" TEXT PRIMARY KEY,
  "user_id" TEXT,
  "encrypted_data" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "export_key" TEXT,
  "scope" TEXT NOT NULL,
  "expires_at" TEXT NOT NULL,
  "created_at" TEXT,
  "wrapped_key_bundle" TEXT,
  "connector_key_id" TEXT,
  "connector_wrapping_alg" TEXT,
  "export_revision" INTEGER NOT NULL,
  "export_generated_at" TEXT,
  "source_content_revision" INTEGER,
  "source_manifest_revision" INTEGER,
  "refresh_status" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "consent_export_refresh_jobs" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "consent_token" TEXT NOT NULL,
  "granted_scope" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "trigger_domain" TEXT,
  "trigger_paths" TEXT NOT NULL,
  "requested_at" TEXT NOT NULL,
  "last_error" TEXT,
  "attempt_count" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "internal_access_events" (
  "id" INTEGER PRIMARY KEY,
  "token_id" TEXT NOT NULL,
  "user_id" TEXT NOT NULL,
  "agent_id" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "issued_at" INTEGER NOT NULL,
  "expires_at" INTEGER,
  "revoked_at" INTEGER,
  "metadata" TEXT,
  "token_type" TEXT,
  "request_id" TEXT,
  "scope_description" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_blobs" (
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "segment_id" TEXT NOT NULL,
  "ciphertext" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "tag" TEXT NOT NULL,
  "algorithm" TEXT NOT NULL,
  "content_revision" INTEGER NOT NULL,
  "manifest_revision" INTEGER NOT NULL,
  "size_bytes" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  PRIMARY KEY ("user_id", "domain", "segment_id")
);

CREATE TABLE IF NOT EXISTS "pkm_data" (
  "user_id" TEXT PRIMARY KEY,
  "encrypted_data_ciphertext" TEXT NOT NULL,
  "encrypted_data_iv" TEXT NOT NULL,
  "encrypted_data_tag" TEXT NOT NULL,
  "algorithm" TEXT,
  "data_version" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_index" (
  "user_id" TEXT PRIMARY KEY,
  "available_domains" TEXT NOT NULL,
  "domain_summaries" TEXT NOT NULL,
  "computed_tags" TEXT NOT NULL,
  "activity_score" REAL,
  "last_active_at" TEXT,
  "total_attributes" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "model_version" INTEGER NOT NULL,
  "last_upgraded_at" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_manifests" (
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "manifest_version" INTEGER NOT NULL,
  "structure_decision" TEXT NOT NULL,
  "summary_projection" TEXT NOT NULL,
  "top_level_scope_paths" TEXT NOT NULL,
  "externalizable_paths" TEXT NOT NULL,
  "segment_ids" TEXT NOT NULL,
  "path_count" INTEGER NOT NULL,
  "externalizable_path_count" INTEGER NOT NULL,
  "last_structured_at" TEXT NOT NULL,
  "last_content_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "domain_contract_version" INTEGER NOT NULL,
  "readable_summary_version" INTEGER NOT NULL,
  "upgraded_at" TEXT,
  PRIMARY KEY ("user_id", "domain")
);

CREATE TABLE IF NOT EXISTS "pkm_manifest_paths" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "json_path" TEXT NOT NULL,
  "parent_path" TEXT,
  "path_type" TEXT NOT NULL,
  "segment_id" TEXT NOT NULL,
  "scope_handle" TEXT,
  "exposure_eligibility" INTEGER NOT NULL,
  "consent_label" TEXT,
  "sensitivity_label" TEXT,
  "source_agent" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_events" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "operation_type" TEXT NOT NULL,
  "segment_ids" TEXT NOT NULL,
  "path_set" TEXT NOT NULL,
  "source_agent" TEXT,
  "confidence" REAL,
  "prior_manifest_version" INTEGER,
  "new_manifest_version" INTEGER,
  "metadata" TEXT NOT NULL,
  "created_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_scope_registry" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "scope_handle" TEXT NOT NULL,
  "scope_label" TEXT NOT NULL,
  "segment_ids" TEXT NOT NULL,
  "sensitivity_tier" TEXT NOT NULL,
  "scope_kind" TEXT NOT NULL,
  "exposure_enabled" INTEGER NOT NULL,
  "manifest_version" INTEGER NOT NULL,
  "summary_projection" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "visibility_posture" TEXT NOT NULL,
  "default_projection_ready" INTEGER NOT NULL,
  "default_projection_updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "pkm_default_available_projections" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "domain" TEXT NOT NULL,
  "scope" TEXT NOT NULL,
  "scope_handle" TEXT,
  "top_level_scope_path" TEXT NOT NULL,
  "projection_payload" TEXT NOT NULL,
  "projection_hash" TEXT NOT NULL,
  "projection_version" INTEGER NOT NULL,
  "manifest_version" INTEGER,
  "content_revision" INTEGER,
  "source_content_revision" INTEGER,
  "source_manifest_revision" INTEGER,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "revoked_at" TEXT,
  "revoked_reason" TEXT,
  "metadata" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pkm_migration_state" (
  "user_id" TEXT PRIMARY KEY,
  "status" TEXT NOT NULL,
  "source_model" TEXT NOT NULL,
  "legacy_blob_present" INTEGER NOT NULL,
  "cutover_started_at" TEXT,
  "migrated_at" TEXT,
  "last_error" TEXT,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "vault_keys" (
  "user_id" TEXT PRIMARY KEY,
  "vault_status" TEXT NOT NULL,
  "vault_key_hash" TEXT,
  "primary_method" TEXT NOT NULL,
  "primary_wrapper_id" TEXT NOT NULL,
  "recovery_encrypted_vault_key" TEXT,
  "recovery_salt" TEXT,
  "recovery_iv" TEXT,
  "first_login_at" INTEGER,
  "last_login_at" INTEGER,
  "login_count" INTEGER NOT NULL,
  "pre_onboarding_completed" INTEGER,
  "pre_onboarding_skipped" INTEGER,
  "pre_onboarding_completed_at" INTEGER,
  "pre_nav_tour_completed_at" INTEGER,
  "pre_nav_tour_skipped_at" INTEGER,
  "pre_state_updated_at" INTEGER,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  "user_email" TEXT
);

CREATE TABLE IF NOT EXISTS "vault_key_wrappers" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "method" TEXT NOT NULL,
  "wrapper_id" TEXT NOT NULL,
  "encrypted_vault_key" TEXT NOT NULL,
  "salt" TEXT NOT NULL,
  "iv" TEXT NOT NULL,
  "passkey_credential_id" TEXT,
  "passkey_prf_salt" TEXT,
  "passkey_rp_id" TEXT,
  "passkey_provider" TEXT,
  "passkey_device_label" TEXT,
  "passkey_last_used_at" INTEGER,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_push_tokens" (
  "id" INTEGER PRIMARY KEY,
  "user_id" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "platform" TEXT NOT NULL,
  "created_at" TEXT,
  "updated_at" TEXT
);

CREATE TABLE IF NOT EXISTS "runtime_persona_state" (
  "user_id" TEXT PRIMARY KEY,
  "last_active_persona" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "user_email" TEXT
);

CREATE TABLE IF NOT EXISTS "developer_applications" (
  "id" INTEGER PRIMARY KEY,
  "slug" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "contact_name" TEXT,
  "contact_email" TEXT NOT NULL,
  "support_url" TEXT,
  "policy_url" TEXT,
  "website_url" TEXT,
  "use_case" TEXT,
  "requested_tool_groups" TEXT NOT NULL,
  "requested_agent_id" TEXT,
  "status" TEXT NOT NULL,
  "notes" TEXT,
  "reviewed_at" INTEGER,
  "reviewed_by" TEXT,
  "rejection_reason" TEXT,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "developer_apps" (
  "app_id" TEXT PRIMARY KEY,
  "application_id" INTEGER,
  "agent_id" TEXT NOT NULL,
  "display_name" TEXT NOT NULL,
  "contact_email" TEXT NOT NULL,
  "support_url" TEXT,
  "policy_url" TEXT,
  "website_url" TEXT,
  "status" TEXT NOT NULL,
  "allowed_tool_groups" TEXT NOT NULL,
  "approved_at" INTEGER,
  "approved_by" TEXT,
  "notes" TEXT,
  "created_at" INTEGER NOT NULL,
  "updated_at" INTEGER NOT NULL,
  "owner_firebase_uid" TEXT,
  "owner_email" TEXT,
  "owner_display_name" TEXT,
  "owner_provider_ids" TEXT NOT NULL,
  "brand_image_url" TEXT
);

CREATE TABLE IF NOT EXISTS "developer_tokens" (
  "id" INTEGER PRIMARY KEY,
  "app_id" TEXT NOT NULL,
  "token_prefix" TEXT NOT NULL,
  "token_hash" TEXT NOT NULL,
  "label" TEXT,
  "created_by" TEXT,
  "revoked_by" TEXT,
  "created_at" INTEGER NOT NULL,
  "revoked_at" INTEGER,
  "last_used_at" INTEGER,
  "last_used_ip" TEXT,
  "last_used_user_agent" TEXT
);

-- WARNING: table users not found in live schema, skipped
